import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AuthProvider from "./context/sessionprovider";
import ValueSelectionProvider from "./context/optionsvalueprovider";
import Footer from "@/components/Footer";
import { ApolloWrapper } from "./ApolloWrapper"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <ApolloWrapper>
        <AuthProvider>
          <ValueSelectionProvider>
            
            <Navbar />
            {children}
            <Footer />
            
          </ValueSelectionProvider>
        </AuthProvider>
        </ApolloWrapper>
      </body>


    </html>
  );
}
